#!/usr/bin/env ruby

require 'httparty'
require 'trollop'
require 'yaml'

def parse_story_file(file, opts)
  groups = YAML.load_file(file)

  result = []
  groups.each do |name, attrs|
    if opts[:interactive]
      print("Include group \"#{name}\"? [y/N] ")
      next unless STDIN.gets.chomp.downcase == 'y'
    else
      next unless opts[:all] || opts[:groups].include?(name)
    end

    label = attrs['labels'] || name

    ['chores', 'features', 'bugs', 'releases'].each do |story_type|
      stories = attrs[story_type]

      unless stories.nil?
        defaults = {
          'labels' => label,
          'story_type' => story_type.chop
        }

        result += stories.map do |story|
          story = {'name' => story} if story.is_a? String
          defaults.merge(story)
        end
      end
    end
  end
  result
end

def parse_stories(opts)
  opts[:files].map {|f| parse_story_file(f, opts)}.flatten(1).reverse
end

def bootstrap_stories(opts)
  project_stories_url = "https://www.pivotaltracker.com/services/v3/projects/#{opts[:project]}/stories"
  http_options = {headers: {'X-TrackerToken' => opts[:token]}}

  $stdout.sync = true

  parse_stories(opts).each do |story|
    print "Loading \"[#{story['labels']}] #{story['name']}\"........"
    response = HTTParty.post(project_stories_url, http_options.merge(body: {story: story}))
    if response.code >= 400
      puts "Fail!"
      puts "An error occurred while loading stories:"
      puts response.parsed_response["response"]["__content__"]
      puts "Exiting"
      exit false
    end
    puts "Done!"
  end
end


def parse_options
  opts = Trollop::options do
    banner <<-EOS
Loads stories into pivotal

Usage:
       pivotal_bootstrap [options] <filenames>*


where <filenames> are a list of YAML files containing stories to load.

See stories.yml for details on the YAML format.

Available [options]:
EOS

    opt :all, "Import all group in the given files without prompting"
    opt :groups, "A space-separated list of groups to import", type: :strings
    opt :token, "Your Pivotal API token.  You may also set this in ~/.pivotal_tracker with the text 'token: <your token>", type: :strings
    opt :project, "Pivotal project id from the project URL", type: :string, required: true
  end

  opts[:files] = ARGV
  opts[:files] << 'stories.yml' if opts[:files].size == 0 && File.exist?('stories.yml')

  opts[:groups] ||= []
  opts[:interactive] ||= !opts[:all] && opts[:groups].size == 0

  unless opts[:token]
    token_file_path = "#{Dir.home}/.pivotal_tracker"
    if File.exist?(token_file_path)
      opts[:token] = YAML.load_file(token_file_path)['token']
    end

    Trollop::die "You must specify a token on the command line or ~/.pivotal_tracker" unless opts[:token]
  end

  Trollop::die "Please specify at least one filename containing stories to import" unless ARGV.length > 0

  opts
end


bootstrap_stories(parse_options)
